import pygame as pg
## SCREEN ##
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
SCREEN = pg.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

## SCENES ##
CURRENT_SCENE_INDEX = 0

## MAIN MENU ##
MAIN_MENU_CURRENT_OPTION_INDEX = 0

## OPTIONS SCREEN ##
OPTIONS_SCREEN_CURRENT_OPTION_INDEX = 0
OPTIONS_SCREEN_CURRENT_RESOLUTION_INDEX = 0
OPTIONS_SCREEN_CURRENT_RESOLUTION_TEMP_INDEX = 0
OPTIONS_SCREEN_CURRENT_DIFFICULTY_INDEX = 0
OPTIONS_SCREEN_CURRENT_DIFFICULTY_TEMP_INDEX = 0
OPTIONS_SCREEN_CURRENT_GRID_INDEX = 0
OPTIONS_SCREEN_CURRENT_GRID_TEMP_INDEX = 0
OPTIONS_SCREEN_CURRENT_GRID_SIZE_INDEX = 0
OPTIONS_SCREEN_CURRENT_GRID_SIZE_TEMP_INDEX = 0

## PLAY SCREEN ##
PLAY_SCREEN_CURRENT_OPTION_INDEX = 0
PAUSE_CURRENT_OPTION_INDEX = 0

## INPUT ##
MOUSE_POS = pg.mouse.get_pos()

## COLORS ##

#                R    G    B
GRAY         = (100, 100, 100)
CHARCOAL     = (50,   50,  50)
NAVYBLUE     = ( 60,  60, 100)
WHITE        = (255, 255, 255)
RED          = (255,   0,   0)
GREEN        = (  0, 255,   0)
FOREST_GREEN = ( 31, 162,  35)
BLUE         = (  0,   0, 255)
SKY_BLUE     = ( 39, 145, 251)
YELLOW       = (255, 255,   0)
ORANGE       = (255, 128,   0)
PURPLE       = (255,   0, 255)
CYAN         = (  0, 255, 255)
BLACK        = (  0,   0,   0)
NEAR_BLACK   = ( 19,  15,  48)
COMBLUE      = (233, 232, 255)
GOLD         = (255, 215,   0)

BG_COLOR = BLACK
TITLE_COLOR = GREEN
BUTTON_DEFAULT_COLOR = WHITE
BUTTON_HOVERED_COLOR = RED
BUTTON_SELECTED_COLOR = GREEN
TEXTBOX_COLOR = GRAY

## DECORATOR ##
FONT_FAMILY = "arial"
FONT_SIZE = 25
TITLE_FONT_SIZE = 72
BUTTON_FONT_SIZE = 40
TEXTBOX_FONT_SIZE = 32

## GAME CONDITION ##
GAME_CLOSE = False
GAME_OVER = False
GAME_PAUSED = False
FIRST_GAME_LOOP = False
GRID_SIZE = 10
NUM_FOOD_NEEDED_FOR_FEVER_TIME = 10
FEVER_TIME_MAX = 7

## GAME SPEED ##
CLOCK = pg.time.Clock()
FPS = 30

## SNAKE ATTRIBUTES ##
SNAKE_SPEED = 20